# Generated by Django 4.2.3 on 2023-08-22 09:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_type", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=13)),
                ("problem", models.TextField(blank=True)),
                ("address", models.CharField(max_length=50)),
                ("post_time", models.DateTimeField(default=datetime.date(2023, 8, 22))),
                ("complete_time", models.DateTimeField(null=True)),
                ("message_id", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("act_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationWorkerAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("comment", models.CharField(max_length=255)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_type", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
                ("services", models.CharField(max_length=350)),
                ("photo", models.ImageField(upload_to="images/")),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worker_type", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("user_id", models.CharField(max_length=50)),
                (
                    "applications",
                    models.ManyToManyField(
                        through="main.ApplicationWorkerAssociation",
                        to="main.application",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="applicationworkerassociation",
            name="worker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.worker"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="workers",
            field=models.ManyToManyField(
                through="main.ApplicationWorkerAssociation", to="main.worker"
            ),
        ),
    ]
