# Generated by Django 4.2.3 on 2023-08-22 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="post_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
