# Generated by Django 4.2.3 on 2023-08-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_application_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
