# Generated by Django 4.2.3 on 2023-08-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_application_price_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
    ]
