# Generated by Django 4.2.3 on 2023-08-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_worker_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='act_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='worker',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
