# Generated by Django 4.2.3 on 2023-09-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_application_act_name_alter_application_problem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='act_name',
        ),
        migrations.AddField(
            model_name='application',
            name='act_id',
            field=models.IntegerField(default=0),
        ),
    ]
