# Generated by Django 4.2.3 on 2023-09-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_application_act_name_application_act_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
