# Generated by Django 4.2.3 on 2023-10-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_worker_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='take_time',
            field=models.DateTimeField(null=True),
        ),
    ]
